### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by TheSavior22** [Slimefun/Slimefun4#2751]
## :round_pushpin: Description (REQUIRED)

 when users click items info in slimefun guide

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1.  open slimefun guide and click item
2. 
3. 

## :scroll: Server Log

Could not pass event InventoryClickEvent to Slimefun vDEV - 791 (git d8aaf006)
java.lang.NoSuchMethodError: io.github.thebusybiscuit.slimefun4.core.SlimefunRegistry.getGuideLayout(Lio/github/thebusybiscuit/slimefun4/core/guide/SlimefunGuideMode;)Lio/github/thebusybiscuit/slimefun4/core/guide/SlimefunGuideImplementation;
at io.github.seggan.liquid.categories.MixerCategory.lambda$open$0(MixerCategory.java:60) ~[?:?]
at me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.MenuListener.onClick(MenuListener.java:56) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor769.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-437]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-437]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-437]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-437]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2540) ~[patched_1.16.5.jar:git-Paper-437]
at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-437]
at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-437]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-437]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-437]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-437]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-437]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-437]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1132) ~[patched_1.16.5.jar:git-Paper-437]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1125) ~[patched_1.16.5.jar:git-Paper-437]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-437]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1261) ~[patched_1.16.5.jar:git-Paper-437]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.5.jar:git-Paper-437]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-437]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

## :compass: Environment (REQUIRED)

Installed Addons: (28)
>.... [00:50:38 INFO]: ExtraTools vDEV - 23 (git 9299a65c)
>.... [00:50:38 INFO]: FoxyMachines vDEV - 11 (git d6bd73c4)
>.... [00:50:38 INFO]: SlimefunOreChunks vDEV - 12 (git e3700851)
>.... [00:50:38 INFO]: SensibleToolbox vDEV - 38 (git 04168f4f)
>.... [00:50:38 INFO]: ExtraGear vDEV - 12 (git 4570ea2c)
>.... [00:50:38 INFO]: ClayTech v1.2.20
>.... [00:50:38 INFO]: InfinityExpansion vDEV - 65 (git f3b719c1)
>.... [00:50:38 INFO]: SFCalc vDEV - 14 (git 8d205b67)
>.... [00:50:38 INFO]: ElectricSpawners vDEV - 21 (git 8efab150)
>.... [00:50:38 INFO]: ExtraHeads vDEV - 20 (git 9ff9e0c9)
>.... [00:50:38 INFO]: MobCapturer vDEV - 13 (git 79bbd87e)
>.... [00:50:38 INFO]: SlimyTreeTaps vDEV - 17 (git 8f3e755b)
>.... [00:50:38 INFO]: ColoredEnderChests vDEV - 20 (git 2f2c1dfc)
>.... [00:50:38 INFO]: TranscEndence vDEV - 22 (git 7660c9f0)
>.... [00:50:38 INFO]: FluffyMachines vDEV - 63 (git 3cad37cd)
>.... [00:50:38 INFO]: ChestTerminal vDEV - 40 (git d302d3ec)
>.... [00:50:38 INFO]: DyedBackpacks vDEV - 13 (git 964b2d55)
>.... [00:50:38 INFO]: SoundMuffler vDEV - 19 (git 5caef292)
>.... [00:50:38 INFO]: SlimefunWarfare vDEV - 12 (git d83ec124)
>.... [00:50:38 INFO]: EcoPower vDEV - 3 (git 18ba903d)
>.... [00:50:38 INFO]: HotbarPets vDEV - 34 (git ee2130bb)
>.... [00:50:38 INFO]: SlimefunLuckyBlocks vDEV - 31 (git 6fa9afbd)
>.... [00:50:38 INFO]: ExoticGarden vDEV - 66 (git eb90e45d)
>.... [00:50:38 INFO]: HeadLimiter vDEV - 1 (git 3fbbe7d6)
>.... [00:50:38 INFO]: Liquid vDEV - 7 (git 1ec76abf)
>.... [00:50:38 INFO]: LiteXpansion vDEV - 124 (git 0e449831)
>.... [00:50:38 INFO]: SoulJars vDEV - 21 (git 59212953)

 - Server Software: 
 - Minecraft Version: paper-1.16.5-437.jar
 - Slimefun Version: Slimefun vDEV - 791 (git d8aaf006)
 - CS-CoreLib Version: CS-CoreLib - DEV 92 (git e9150)

**Comment by TheBusyBiscuit** [comment]
1. Please use https://pastebin.com when posting errors
2. This error is not from Slimefun, it's from "Liquid", so you should report it to them instead: https://github.com/Seggan/Liquid/issues

**Comment by J3fftw1** [comment]
Really offtopic and sorry everyone that gets an email but is there  a reason you use headlimiter?
