### ISSUE TITLE
Industrial Miner not working

### ISSUE THREAD

**Issue by CoRRupTeD-sHaDow** [Slimefun/Slimefun4#3172]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Good Evening,
I have an Issue with the Industrial Miner.
Everytime someone tries to use it, it just stops after playing the starting Animation and doesn't do anything besides saying that it is running, which is obviously not doing.
In the Console i get a Warning because of it, saying those following things:

[14:30:28 WARN]: [Slimefun] Task #15370 for Slimefun vDEV - 949 (git 6392af00) generated an exception
java.lang.NoSuchMethodError: 'int org.bukkit.World.getMinHeight()'
         at io.github.thebusybiscuit.slimefun4.utils.WorldUtils.getMinHeight(WorldUtils.java:32) ~[?:?]
         at io.github.thebusybiscuit.slimefun4.implementation.items.multiblocks.miner.MiningTask.lambda$run$21(MiningTask.java:186) ~[?:?]
         at me.mrCookieSlime.Slimefun.cscorelib2.scheduling.TaskQueue.lambda$thenRun$1(TaskQueue.java:88) ~[?:?]
         at me.mrCookieSlime.Slimefun.cscorelib2.scheduling.TaskQueue.lambda$run$0(TaskQueue.java:47) ~[?:?]
         at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-416]
         at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-416]
         at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1293) ~[patched_1.16.4.jar:git-Paper-416]
         at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-416]
         at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.4.jar:git-Paper-416]
         at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Paper-416]
         at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-416]
         at java.lang.Thread.run(Thread.java:834) [?:?]

If you need any more detail, tell me

### 📑 Reproduction Steps

As shown in the Video
1. Build your Industrial Miner near any Ore
2. Put Fuel in your Miner and then start it

### 💡 Expected Behavior

That it would mine the Ores in its Range.

### 📷 Screenshots / Videos

https://youtu.be/-JxTKmIg6I8

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

Its the newest Version since 13.07 
Slimefun4 - DEV 949 (git 6392a)

**Comment by WalshyDev** [comment]
You're using a **very** old 1.16 build of Paper. Update it.
