### ISSUE TITLE
starting error

### ISSUE THREAD

**Issue by Yamiru** [Slimefun/Slimefun4#3270]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

starting error

### 📑 Reproduction Steps

starting server

### 💡 Expected Behavior

[09:52:17 WARN]: [Slimefun] Loaded class me.angeschossen.lands.api.integration.LandsIntegration from Lands v5.17.1 which is not a depend, softdepend or loadbefore of this plugin.
[09:52:17 ERROR]: [dough: protection] An Error occured while registering the Protection Module: "Lands" v5.17.1
java.lang.IllegalArgumentException: The provided plugin parameter must be a instance of your plugin on not the Lands plugin.
        at me.angeschossen.lands.api.integration.LandsIntegration.<init>(?:59) ~[Lands-5.17.1.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.modules.LandsProtectionModule.load(LandsProtectionModule.java:34) ~[Slimefun4 - DEV 971 (git 19c7e).jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.registerModule(ProtectionManager.java:120) ~[Slimefun4 - DEV 971 (git 19c7e).jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.registerModule(ProtectionManager.java:113) ~[Slimefun4 - DEV 971 (git 19c7e).jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.<init>(ProtectionManager.java:72) ~[Slimefun4 - DEV 971 (git 19c7e).jar:?]
        at io.github.thebusybiscuit.slimefun4.integrations.IntegrationsManager.onServerStart(IntegrationsManager.java:143) ~[Slimefun4 - DEV 971 (git 19c7e).jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-266]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1221) ~[patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-266]
        at java.lang.Thread.run(Thread.java:831) [?:?]

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Slimefun4 - DEV 971 (git 19c7e)  (latest)

### 🧭 Other plugins

Lands-5.17.1 (latest)

**Comment by TheBusyBiscuit** [comment]
Always use pastebin when posting errors.

Also, that error is not from Slimefun...
It is from dough / Lands.
