### ISSUE TITLE
BlockBreak bug  console log

### ISSUE THREAD

**Issue by zwrumpy** [Slimefun/Slimefun4#3351]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

BlockBreak bug console log

### 📑 Reproduction Steps

only console log

### 💡 Expected Behavior

no warning message at console

### 📜 Server Log

[21:06:39 ERROR]: [Slimefun] Item "CARGO_NODE_OUTPUT_ADVANCED" from Slimefun vDEV - 984 (git 82978f7d) has caused an Error! [21:06:39 ERROR]: [Slimefun] You can report it here: https://github.com/Slimefun/Slimefun4/issues [21:06:39 ERROR]: [Slimefun] Could not pass "BlockBreakHandler" for AdvancedCargoOutputNode - 'CARGO_NODE_OUTPUT_ADVANCED' (Slimefun vDEV - 984 (git 82978f7d)) java.lang.ArrayIndexOutOfBoundsException: Index 28 out of bounds for length 27         at java.util.Arrays$ArrayList.get(Arrays.java:4164) ~[?:?]         at net.minecraft.core.NonNullList.get(NonNullList.java:47) ~[patched_1.17.1.jar:git-Airplane-102]         at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftInventoryCustom$MinecraftInventory.getItem(CraftInventoryCustom.java:105) ~[patched_1.17.1.jar:git-Airplane-102]         at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftInventory.getItem(CraftInventory.java:49) ~[patched_1.17.1.jar:git-Airplane-102]         at me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.ChestMenu.getItemInSlot(ChestMenu.java:161) ~[Slimefun4 - DEV 984 (git 82978).jar:?]         at me.mrCookieSlime.Slimefun.api.inventory.BlockMenu.dropItems(BlockMenu.java:105) ~[Slimefun4 - DEV 984 (git 82978).jar:?]         at io.github.thebusybiscuit.slimefun4.implementation.items.cargo.AbstractFilterNode$1.onBlockBreak(AbstractFilterNode.java:62) ~[Slimefun4 - DEV 984 (git 82978).jar:?]         at io.github.thebusybiscuit.slimefun4.implementation.handlers.SimpleBlockBreakHandler.onPlayerBreak(SimpleBlockBreakHandler.java:46) ~[Slimefun4 - DEV 984 (git 82978).jar:?]         at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.lambda$callBlockHandler$2(BlockListener.java:158) ~[Slimefun4 - DEV 984 (git 82978).jar:?]         at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.callItemHandler(SlimefunItem.java:924) ~[Slimefun4 - DEV 984 (git 82978).jar:?]         at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.callBlockHandler(BlockListener.java:158) ~[Slimefun4 - DEV 984 (git 82978).jar:?]         at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockBreak(BlockListener.java:126) ~[Slimefun4 - DEV 984 (git 82978).jar:?]         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor713.execute(Unknown Source) ~[?:?]         at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Airplane-102]         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Airplane-102]         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Airplane-102]         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Airplane-102]         at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:402) ~[app:?]         at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:356) ~[app:?]         at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:316) ~[app:?]         at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1739) ~[app:?]         at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[app:?]         at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[app:?]         at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]         at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Airplane-102]         at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]         at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]         at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1423) ~[patched_1.17.1.jar:git-Airplane-102]         at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Airplane-102]         at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]         at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1401) ~[patched_1.17.1.jar:git-Airplane-102]         at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1394) ~[patched_1.17.1.jar:git-Airplane-102]         at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]         at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1372) ~[patched_1.17.1.jar:git-Airplane-102]         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Airplane-102]         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-102]         at java.lang.Thread.run(Thread.java:831) ~[?:?]

### 💻 Server Software

Airplane

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Slimefun vDEV - 984

**Comment by variananora** [comment]
please paste your logs into pastebin or something similar or just send the whole file, it's hard to read those.
reproduction steps also not really useful, any ideas what you are doing to get this error?
