### ISSUE TITLE
Cant oben the Category

### ISSUE THREAD

**Issue by PYCPlexy** [Slimefun/Slimefun4#3399]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When i try to open the infinity expansion guide, i can take the nether start out and thats in the console

`[14:56:51 ERROR]: Could not pass event InventoryClickEvent to Slimefun vRC - 30 (git fd4b462f)
java.lang.LinkageError: loader constraint violation: loader 'InfinityExpansion - DEV 127 (git 828cf).jar' @34a740a6 wants to load class me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.ChestMenu. A different class with the same name was previously loaded by 'Slimefun4 - RC 30 (git fd4b4).jar' @184db5b1. (me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.ChestMenu is in unnamed module of loader 'Slimefun4 - RC 30 (git fd4b4).jar' @184db5b1, parent loader 'app')
        at io.github.mooy1.infinityexpansion.infinitylib.groups.MultiGroup.openGuide(MultiGroup.java:63) ~[InfinityExpansion - DEV 127 (git 828cf).jar:?]
        at io.github.mooy1.infinityexpansion.infinitylib.groups.MultiGroup.open(MultiGroup.java:55) ~[InfinityExpansion - DEV 127 (git 828cf).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.guide.SurvivalSlimefunGuide.openItemGroup(SurvivalSlimefunGuide.java:235) ~[Slimefun4 - RC 30 (git fd4b4).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.guide.SurvivalSlimefunGuide.lambda$showItemGroup$4(SurvivalSlimefunGuide.java:203) ~[Slimefun4 - RC 30 (git fd4b4).jar:?]
        at me.mrCookieSlime.CSCoreLibPlugin.general.Inventory.MenuListener.onClick(MenuListener.java:56) ~[Slimefun4 - RC 30 (git fd4b4).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor481.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-404]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-404]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-404]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-404]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2807) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-404]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-404]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-404]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-404]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-404]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-404]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-404]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-404]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

### 📑 Reproduction Steps

Open Guide
Click on InfinityExpansion

### 💡 Expected Behavior

Open Category

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

RC 30 & DEV992 (same error with both versions)

### 🧭 Other plugins

InfinityExpansion (DEV - 127)

**Comment by variananora** [comment]
Wrong issue tracker. Please report it to InfinityExpansion here https://github.com/Mooy1/InfinityExpansion/issues
