### ISSUE TITLE
Logblock compatibility

### ISSUE THREAD

**Issue by L4BORG** [Slimefun/Slimefun4#3404]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Not quite sure, saw exception:

```
[19:02:57 ERROR]: [dough: protection] An Error occured while logging for the Protection Module: "LogBlock"
java.lang.NoClassDefFoundError: de/diddiz/util/LoggingUtil
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.loggers.LogBlockLogger.logAction(LogBlockLogger.java:33) ~[Slimefun4.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.logAction(ProtectionManager.java:165) ~[Slimefun4.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.dropItems(BlockListener.java:173) ~[Slimefun4.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockBreak(BlockListener.java:129) ~[Slimefun4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor385.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-404]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-404]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-404]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-404]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:402) ~[app:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:356) ~[app:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:291) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1739) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-404]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-404]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-404]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-404]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-404]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1536) ~[patched_1.17.1.jar:git-Paper-404]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-404]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-404]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

### 📑 Reproduction Steps

Not sure, I think it was players interacting with items.

### 💡 Expected Behavior

N/A

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

> sf versions
[19:06:02 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-404 (MC: 1.17.1)
Slimefun DEV - 990 (git 35e25eb8)
Metrics-Module #28
Java 16

Installed Addons: (3)
  EcoPower vDEV - 5 (git 5c1ecd68)
  SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
  ExoticGarden vDEV - 77 (git a2c4b6d3)

**Comment by L4BORG** [comment]
Actually I think the issue is related to players trying to drop blocks?

Running latest logblock from CI from https://github.com/LogBlock/LogBlock

**Comment by TheBusyBiscuit** [comment]
Neither is this stacktrace from Slimefun, nor does this issue belong here.
The error you posted comes from dough.
