### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Ashiroo** [Slimefun/Slimefun4#3433]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

After updating to new version residence i have only spam, i try downgrade . not work. i try update to new version Slimefun and Residence. not work again. only spam

>.... [04:34:29 WARN]: [Residence] Task #141 for Residence v5.0.1.1 generated an exception
java.lang.NoSuchMethodError: 'void io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.registerModule(org.bukkit.Server, java.lang.String, java.util.function.Function)'
at com.bekvon.bukkit.residence.slimeFun.SlimefunManager.lambda$0(SlimefunManager.java:23) ~[Residence5.0.1.1.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:103) ~[purpur-1.18.1.jar:git-Purpur-1519]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.1.jar:git-Purpur-1519]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1574) ~[purpur-1.18.1.jar:git-Purpur-1519]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1519]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1497) ~[purpur-1.18.1.jar:git-Purpur-1519]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1285) ~[purpur-1.18.1.jar:git-Purpur-1519]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1519]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

### 📑 Reproduction Steps

Just start server and spam begin..

### 💡 Expected Behavior

Maybe new version of residence corupted

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/98004199/150062529-228ee3d0-bebf-4054-b396-cb28e0b4200a.png)

### 🧭 Other plugins

![Snímka](https://user-images.githubusercontent.com/98004199/150062361-715ef532-8fd8-4bda-9390-88ec3cc9802d.PNG)

**Comment by variananora** [comment]
Protection plugin integration is reported through dough [here](https://github.com/baked-libs/dough/issues)
