### ISSUE TITLE
Advanced Industrial Miner Bug

### ISSUE THREAD

**Issue by Garzbaen** [Slimefun/Slimefun4#3527]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When trying to use the advanced industrial miner, it always uses up a lava bucket (The fuel) and just breaks. The pistons don't move which indicates that its not searching for ores to mine and let alone it doesn't mine anything even though there are surrounding ores , but for some strange reason when I right click the blast furnace it tells me that the machine is still running. I've tried restarting my aternos server, changing the machine's location both in x and y manner but it still does the same. And before it completely freeze, it uses up the lava, the pistons move and then it pretends that it mined an ore before completely freezing and breaking.
![image](https://user-images.githubusercontent.com/103429482/162741106-844c9a1a-a6cc-4456-b00a-a04df800a138.png)

![image](https://user-images.githubusercontent.com/103429482/162741149-74617a4b-e643-4b1f-9d27-0697db4e4cd2.png)

### 📑 Reproduction Steps

1. Just build the advanced industrial miner normally...

### 💡 Expected Behavior

I expected it to work and mine ores 11x11

### 📷 Screenshots / Videos

![image](https://user-images.githubusercontent.com/103429482/162741190-0a14d10e-7113-4cb7-ad61-c9f776894a36.png)

![image](https://user-images.githubusercontent.com/103429482/162741106-844c9a1a-a6cc-4456-b00a-a04df800a138.png)

### 📜 Server Log

(TaskQueue.java:48) ~[?:?] 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d] 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d] 	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1061) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d] 	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d] 	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d] 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d] 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d] 	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

Slimefun 1008

### 🧭 Other plugins

Slimefun 1008

**Comment by ybw0014** [comment]
Please provide full log, current one doesn't tell anything.

**Comment by Garzbaen** [comment]
> Please provide full log, current one doesn't tell anything.

<html>
<body>




Task #88 for Slimefun vDEV - 1009 (git 429ff506) generated an exception
398 | java.lang.NoSuchMethodError: org.bukkit.World.getMinHeight()I
399 | at io.github.thebusybiscuit.slimefun4.utils.WorldUtils.getMinHeight(WorldUtils.java:34) ~[?:?]
400 | at io.github.thebusybiscuit.slimefun4.implementation.items.multiblocks.miner.MiningTask.lambda$run$22(MiningTask.java:193) ~[?:?]
401 | at io.github.thebusybiscuit.slimefun4.libraries.dough.scheduling.TaskQueue.lambda$thenRun$1(TaskQueue.java:89) ~[?:?]
402 | at io.github.thebusybiscuit.slimefun4.libraries.dough.scheduling.TaskNode.execute(TaskNode.java:42) ~[?:?]
403 | at io.github.thebusybiscuit.slimefun4.libraries.dough.scheduling.TaskQueue.lambda$run$0(TaskQueue.java:48) ~[?:?]
404 | at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
405 | at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
406 | at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1061) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
407 | at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
408 | at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
409 | at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
410 | at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
411 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
412 | [23:14:34] [Server thread/WARN]: [Slimefun] Task #111 for Slimefun vDEV - 1009 (git 429ff506) generated an exception
413 | java.lang.NoSuchMethodError: org.bukkit.World.getMinHeight()I
414 | at io.github.thebusybiscuit.slimefun4.utils.WorldUtils.getMinHeight(WorldUtils.java:34) ~[?:?]
415 | at io.github.thebusybiscuit.slimefun4.implementation.items.multiblocks.miner.MiningTask.lambda$run$22(MiningTask.java:193) ~[?:?]
416 | at io.github.thebusybiscuit.slimefun4.libraries.dough.scheduling.TaskQueue.lambda$thenRun$1(TaskQueue.java:89) ~[?:?]
417 | at io.github.thebusybiscuit.slimefun4.libraries.dough.scheduling.TaskNode.execute(TaskNode.java:42) ~[?:?]
418 | at io.github.thebusybiscuit.slimefun4.libraries.dough.scheduling.TaskQueue.lambda$run$0(TaskQueue.java:48) ~[?:?]
419 | at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
420 | at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
421 | at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1061) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
422 | at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
423 | at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
424 | at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
425 | at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
426 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
427

<br class="Apple-interchange-newline">
</body>
</html>Task #88 for Slimefun vDEV - 1009 (git 429ff506) generated an exception
java.lang.NoSuchMethodError: org.bukkit.World.getMinHeight()I
	at io.github.thebusybiscuit.slimefun4.utils.WorldUtils.getMinHeight(WorldUtils.java:34) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.items.multiblocks.miner.MiningTask.lambda$run$22(MiningTask.java:193) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.libraries.dough.scheduling.TaskQueue.lambda$thenRun$1(TaskQueue.java:89) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.libraries.dough.scheduling.TaskNode.execute(TaskNode.java:42) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.libraries.dough.scheduling.TaskQueue.lambda$run$0(TaskQueue.java:48) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:[400](https://aternos.org/log/#L400)) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1061) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[23:14:34] [Server thread/WARN]: [Slimefun] Task #111 for Slimefun vDEV - 1009 (git 429ff506) generated an exception
java.lang.NoSuchMethodError: org.bukkit.World.getMinHeight()I
	at io.github.thebusybiscuit.slimefun4.utils.WorldUtils.getMinHeight(WorldUtils.java:34) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.items.multiblocks.miner.MiningTask.lambda$run$22(MiningTask.java:193) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.libraries.dough.scheduling.TaskQueue.lambda$thenRun$1(TaskQueue.java:89) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.libraries.dough.scheduling.TaskNode.execute(TaskNode.java:42) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.libraries.dough.scheduling.TaskQueue.lambda$run$0(TaskQueue.java:48) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1061) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:git-Spigot-9639cf7-4b9bc9d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

**Comment by Garzbaen** [comment]
> Please provide full log, current one doesn't tell anything.

Please tell me if this helps

**Comment by Boomer-1** [comment]
what version of Java are you running?

**Comment by Garzbaen** [comment]
> what version of Java are you running?

On aternos its java 8, on my computer it's version 16.0.1

**Comment by Boomer-1** [comment]
The error looks like it was a java command that's for a more updated version of Java. I would update to Java 16 or 17 if possible.

**Comment by Boomer-1** [comment]
Aternos should provide that for you.

**Comment by Garzbaen** [comment]
> Aternos should provide that for you.

I just Updated my java right now, I have the latest 1.8.0
I'll just now

**Comment by Boomer-1** [comment]
1.8 is not the latest. on the server you need to run Java 16 or higher. 1.8 is also known as Java 8 which is an old version

**Comment by qwertyuioplkjhgfd** [comment]
Slimefun does not require Java 16 (yet). The issue is that Slimefun is using API that was only added in 1.16.5, so you are probably running minecraft 1.16.0 - 1.16.4

**Comment by ybw0014** [comment]
im typing about that lol.
you are using 1.16 version below 1.16.5, and `getMinHeight`only exists above 1.16.5

**Comment by Garzbaen** [comment]
So Ill just update my minecraft to 1.16.5 and get java 16 right?

**Comment by ybw0014** [comment]
no need to get java 16, but we recommend it

**Comment by Garzbaen** [comment]
Since you guys recommend and I'm a moron, send me the link to download it please, thanks!

**Comment by Garzbaen** [comment]
It finally works, guys thanks so so so much!
