### ISSUE TITLE
Incompatibility with IAxPresenceFootsteps

### ISSUE THREAD

**Issue by Garfieldwxg55** [Slimefun/Slimefun4#3575]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Hi, I was recently creating an SMP server, and I tried installing ItemsAdder, Slimefun, and an ItemsAdder addon called IAxPresenceFootsteps, which adds compatibility for the mod Presence Footsteps to ItemsAdder.
https://github.com/Andre601/IAxPresenceFootsteps
However, when I tested the mod, I noticed that when Slimefun was installed, it caused IAxPresenceFootsteps to load before ItemsAdder instead of after, and since ItemsAdder is a dependency of IAxPresenceFootsteps, the plugin doesn't work.

### 📑 Reproduction Steps

1. Download the latest versions of Slimefun, ItemsAdder, and IAxPresenceFootsteps to a server.
2. Start the server
3. Notice that IAxPresenceFootsteps loads before ItemsAdder instead of after like it should?

### 💡 Expected Behavior

I expected IAxPresenceFootsteps to load after ItemsAdder like it normally does instead of before as it did here.

### 📜 Server Log

https://pastebin.com/mc7i7tZP

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

Slimefun version DEV - 1014 (git f431aa6d)

### 🧭 Other plugins

ItemsAdder, IAxPresenceFootsteps

**Comment by Andre601** [comment]
Heyo. Dev of IAxPresenceFootsteps here to give some extra info real quick.

Before you claim it's an issue on my end: No. My plugin has `ItemsAdder` defined as Softdepend in its plugin.yml (I dislike using depend because of ugly stacktraces) and I also run a basic "if ItemsAdder not enabled" check to disable the plugin in the onEnable (not onLoad) part.

Relevant lines:
https://github.com/Andre601/IAxPresenceFootsteps/blob/45db1168e745337f57412ebd8b6f50c8ddba02eb/src/main/resources/plugin.yml#L8-L9

https://github.com/Andre601/IAxPresenceFootsteps/blob/45db1168e745337f57412ebd8b6f50c8ddba02eb/src/main/java/ch/andre601/iaxpresencefootsteps/IAxPresenceFootsteps.java#L38-L42

I have discussed this with the user in Discord and after trial and error did we figure out that Slimefun for whatever reason is messing up the plugin load and enable behaviour, which certainly isn't good.

Either way, just wanted to leave this here to make clear that I'm not manipulating the Spigot Server on runtime or whatever....

**Comment by Phoenix-Starlight** [comment]
Just curious, would putting a depend on Slimefun make it work then?

**Comment by Andre601** [comment]
It seems that this is an issue caused by the server itself.
Tho, given that testing with just Slimefun, ItemsAdder and IAxPresenceFootsteps yields the same results makes me assume there is an issue in SlimeFun's end.

Either way, the issue I talk about is this one: https://github.com/PaperMC/Paper/issues/5992

**Comment by Phoenix-Starlight** [comment]
It may be that Iris and Viaversion is missing here, but I'm not certain if this is ItemsAdder:
```
[16:26:03] [Server thread/ERROR]: Could not load 'plugins\itemsadder-blocks-injector_0.0.4.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [Iris, ViaVersion]. Please download and install these plugins to run 'ItemsAdderBlocksInjector'.
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:291) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-367]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-367]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-367]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-367]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by JustAHuman-xD** [comment]
Is this still a problem? As the relevant issue has since been fixed (as of a week ago)

**Comment by JustAHuman-xD** [comment]
@Andre601 @FivesBlue Can anyone confirm that this is still an issue otherwise this'll be closed 👍

**Comment by Andre601** [comment]
I think this is a more general issue with circular dependencies in Spigot, so not a Slimefun issue I would say.

**Comment by JustAHuman-xD** [comment]
> I think this is a more general issue with circular dependencies in Spigot, so not a Slimefun issue I would say.

So all good to be closed here then?

**Comment by JustAHuman-xD** [comment]
Going to close this for now then 👍
