### ISSUE TITLE
Pickaxe of Containment not working

### ISSUE THREAD

**Issue by melwinVIP** [Slimefun/Slimefun4#3808]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Pickaxe of containment don't work, me and other people tried to use it to get broken spawner but only thing that happen is you get exp orbs from it.
Serwer is on 
PaperSpigot 1.19.3 build 323

### 📑 Reproduction Steps

1. Get pickaxe of containment
2. Get spawner via command /sf cheat
3. Get spawning egg for example /give @p minecraft:skeleton_spawn_egg
4. Place spawner on the ground
5. Right click spawning egg on the spawner
6. Destroy spawner using pickaxe of containment

### 💡 Expected Behavior

i expected spawner to drop as a broken spawner 

### 📜 Server Log

https://pastebin.com/ChN92Lh5

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

![obraz](https://user-images.githubusercontent.com/129098090/228013775-4d6f02ae-82b4-4c80-bbd2-14a4b4c729fd.png)

### 🧭 Other plugins

![obraz](https://user-images.githubusercontent.com/129098090/228014517-eb1a3d32-0150-449d-b1d3-1b980550983e.png)

**Comment by Boomer-1** [comment]
couple things also stand out here. You can't get a vanilla spawner cage from /sf cheat. you can only get those from creative mode or commands outside of slimefun. Slimefun would have given a reinforced, or broken spawner depending on what you selected

**Comment by Boomer-1** [comment]
YBW - 99% sure this is related to mojang changing the mob spawner cage name in 1.19.3.

**Comment by Boomer-1** [comment]
[12:27:44 ERROR]: [Slimefun] Item "PICKAXE_OF_CONTAINMENT" from Slimefun vDEV - 1050 (git 22a7f422) has caused an Error![12:27:44 ERROR]: [Slimefun] You can report it here: https://github.com/Slimefun/Slimefun4/issues
[12:27:44 ERROR]: [Slimefun] Could not pass "ToolUseHandler" for PickaxeOfContainment - 'PICKAXE_OF_CONTAINMENT' (Slimefun vDEV - 1050 (git 22a7f422))
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.GeneratorAccess.s_()" because the return value of "org.bukkit.craftbukkit.v1_19_R2.block.CraftCreatureSpawner.getWorldHandle()" is null
        at org.bukkit.craftbukkit.v1_19_R2.block.CraftCreatureSpawner.setSpawnedType(CraftCreatureSpawner.java:28) ~[paper-1.19.3.jar:git-Paper-322]
        at io.github.thebusybiscuit.slimefun4.implementation.items.blocks.AbstractMonsterSpawner.getItemForEntityType(AbstractMonsterSpawner.java:90) ~[Slimefun4 - DEV 1015 (git 2c4f8).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.items.tools.PickaxeOfContainment.breakSpawner(PickaxeOfContainment.java:78) ~[Slimefun4 - DEV 1015 (git 2c4f8).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.items.tools.PickaxeOfContainment.lambda$getItemHandler$0(PickaxeOfContainment.java:52) ~[Slimefun4 - DEV 1015 (git 2c4f8).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.lambda$callToolHandler$1(BlockListener.java:138) ~[Slimefun4 - DEV 1015 (git 2c4f8).jar:?]
        at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.callItemHandler(SlimefunItem.java:941) ~[Slimefun4 - DEV 1015 (git 2c4f8).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.callToolHandler(BlockListener.java:138) ~[Slimefun4 - DEV 1015 (git 2c4f8).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockBreak(BlockListener.java:122) ~[Slimefun4 - DEV 1015 (git 2c4f8).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor18.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-322]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:369) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:328) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:292) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1875) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-322]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-322]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-322]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-322]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-322]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-322]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-322]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-322]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by melwinVIP** [comment]
> couple things also stand out here. You can't get a vanilla spawner cage from /sf cheat. you can only get those from creative mode or commands outside of slimefun. Slimefun would have given a reinforced, or broken spawner depending on what you selected

yes but me as a admin tried it on reinforced spawner that i placed on the ground and then changed it via spawning egg, but other players are tried to get for example blaze spawner or spider spawner but it don't drop either

**Comment by Boomer-1** [comment]
if you read above you'll see the issue

**Comment by melwinVIP** [comment]
> if you read above you'll see the issue

i mean i didn't get anything like that on the server log, only thing i got is the first 3 line with the time, even if i find and break normall generated spawned

**Comment by melwinVIP** [comment]
Sorry by bad.... now i looked it up at logs and it's all there, i just posted it from console because i didn't know i can check logs at files.

**Comment by mastabaaudio** [comment]
me too
[10:43:22 ERROR]: [Slimefun] Could not pass "ToolUseHandler" for PickaxeOfContainment - 'PICKAXE_OF_CONTAINMENT' (Slimefun vRC - 33 (git 0830fc6d))
java.lang.NullPointerException: Cannot invoke "io.github.thebusybiscuit.slimefun4.implementation.items.blocks.AbstractMonsterSpawner.getItemForEntityType(org.bukkit.entity.EntityType)" because "spawner" is null
        at io.github.thebusybiscuit.slimefun4.implementation.items.tools.PickaxeOfContainment.breakSpawner(PickaxeOfContainment.java:78) ~[Slimefun4-33.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.items.tools.PickaxeOfContainment.lambda$getItemHandler$0(PickaxeOfContainment.java:52) ~[Slimefun4-33.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.lambda$callToolHandler$1(BlockListener.java:138) ~[Slimefun4-33.jar:?]
        at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.callItemHandler(SlimefunItem.java:941) ~[Slimefun4-33.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.callToolHandler(BlockListener.java:138) ~[Slimefun4-33.jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockBreak(BlockListener.java:122) ~[Slimefun4-33.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor488.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1858]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:369) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:328) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:292) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1965) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by mastabaaudio** [comment]
and with the dev version
[11:04:05 ERROR]: [Slimefun] Item "PICKAXE_OF_CONTAINMENT" from Slimefun vDEV - 1050 (git 22a7f422) has caused an Error!
[11:04:05 ERROR]: [Slimefun] You can report it here: https://github.com/Slimefun/Slimefun4/issues
[11:04:05 ERROR]: [Slimefun] Could not pass "ToolUseHandler" for PickaxeOfContainment - 'PICKAXE_OF_CONTAINMENT' (Slimefun vDEV - 1050 (git 22a7f422))
java.lang.NullPointerException: Cannot invoke "io.github.thebusybiscuit.slimefun4.implementation.items.blocks.AbstractMonsterSpawner.getItemForEntityType(org.bukkit.entity.EntityType)" because "spawner" is null
        at io.github.thebusybiscuit.slimefun4.implementation.items.tools.PickaxeOfContainment.breakSpawner(PickaxeOfContainment.java:78) ~[Slimefun4 - DEV 1050 (git 22a7f).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.items.tools.PickaxeOfContainment.lambda$getItemHandler$0(PickaxeOfContainment.java:52) ~[Slimefun4 - DEV 1050 (git 22a7f).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.lambda$callToolHandler$1(BlockListener.java:138) ~[Slimefun4 - DEV 1050 (git 22a7f).jar:?]
        at io.github.thebusybiscuit.slimefun4.api.items.SlimefunItem.callItemHandler(SlimefunItem.java:941) ~[Slimefun4 - DEV 1050 (git 22a7f).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.callToolHandler(BlockListener.java:138) ~[Slimefun4 - DEV 1050 (git 22a7f).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.listeners.BlockListener.onBlockBreak(BlockListener.java:122) ~[Slimefun4 - DEV 1050 (git 22a7f).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor488.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1858]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:369) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:328) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:292) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1965) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by JustAHuman-xD** [comment]
This is caused by some changes present in 1.19.4 and just requires ac spigot bump to fix iirc

**Comment by mastabaaudio** [comment]
Ok, so is there anything I could do to make it work?

**Comment by Boomer-1** [comment]
the code has to be fixed because mojang changed the internal name of the spawner cage

**Comment by JustAHuman-xD** [comment]
Is this still an issue with the latest build?

**Comment by ybw0014** [comment]
Just tested with paper 1.20 9, sf 1060, no errors occurred

**Comment by variananora** [comment]
As ybw tested, this should be resolved. If there is any problem feel free to reopen this issue.
