### ISSUE TITLE
Slimefun error athernos

### ISSUE THREAD

**Issue by eorono** [Slimefun/Slimefun4#3986]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

[15:13:15 ERROR]: Error occurred while enabling Slimefun vDEV - 1103 (git b6b091aa) (Is it up to date?)
java.lang.NullPointerException: Profile name must not be null
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31) ~[authlib-5.0.47.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaSkull.setOwningPlayer(CraftMetaSkull.java:248) ~[paper-1.20.2.jar:git-Paper-207]
	at io.github.thebusybiscuit.slimefun4.libraries.dough.skins.CustomGameProfile.apply(CustomGameProfile.java:40) ~[Slimefun4-1103.jar:?]
	at io.github.thebusybiscuit.slimefun4.libraries.dough.skins.PlayerHead.lambda$getItemStack$1(PlayerHead.java:53) ~[Slimefun4-1103.jar:?]
	at io.github.thebusybiscuit.slimefun4.libraries.dough.skins.PlayerHead.getItemStack(PlayerHead.java:63) ~[Slimefun4-1103.jar:?]
	at io.github.thebusybiscuit.slimefun4.libraries.dough.skins.PlayerHead.getItemStack(PlayerHead.java:51) ~[Slimefun4-1103.jar:?]
	at io.github.thebusybiscuit.slimefun4.utils.SlimefunUtils.getCustomHead(SlimefunUtils.java:246) ~[Slimefun4-1103.jar:?]
	at io.github.thebusybiscuit.slimefun4.core.services.localization.Language.<init>(Language.java:52) ~[Slimefun4-1103.jar:?]
	at io.github.thebusybiscuit.slimefun4.core.services.LocalizationService.<init>(LocalizationService.java:67) ~[Slimefun4-1103.jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.Slimefun.onPluginStart(Slimefun.java:303) ~[Slimefun4-1103.jar:?]
	at io.github.thebusybiscuit.slimefun4.implementation.Slimefun.onEnable(Slimefun.java:247) ~[Slimefun4-1103.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-207]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-207]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-207]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-207]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-207]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-207]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-207]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-207]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-207]
	at java.lang.Thread.run(Unknown Source) ~[?:?]

### 📑 Reproduction Steps

Just started the server, thats it 

### 💡 Expected Behavior

Star without error following the estep of install a plugin on athernos server

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Slimefun vDEV - 1103

**Comment by ybw0014** [comment]
This is known, but someone finally raised an issue about this. Slimefun does not support 1.20.2 yet.

**Comment by variananora** [comment]
Change title to: Slimefun is not supporting 1.20.2

**Comment by iTwins** [comment]
should be fixed by https://github.com/baked-libs/dough/pull/225
