### ISSUE TITLE
cant run in java version "17-internal"

### ISSUE THREAD

**Issue by wibi9424** [Slimefun/Slimefun4#4022]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

when i run server with this plugin, everything is good, server can run and other plugins also normal but in the end of console text before server done! apear, slimefun was disabled, please fix it.

[16:25:43 INFO]: [Slimefun] Paper was detected! Performance optimizations have been applied.
[16:25:43 ERROR]: [Slimefun] Error: Cannot identify Java version - 17-internal
[16:25:43 ERROR]: [Slimefun] Error: Cannot identify Java version - 17-internal
[16:25:43 WARN]: [Slimefun] ****************************************************
[16:25:43 WARN]: [Slimefun] * Your Java version (Java 0) is out of date.
[16:25:43 WARN]: [Slimefun] *
[16:25:43 WARN]: [Slimefun] * We recommend you to update to Java 17.
[16:25:43 WARN]: [Slimefun] * Java 17 is required for newer versions of Minecraft
[16:25:43 WARN]: [Slimefun] * and we would like to utilise all the new features
[16:25:43 WARN]: [Slimefun] * that come with it as soon as possible.
[16:25:43 WARN]: [Slimefun] * Slimefun will also require Java 17 in
[16:25:43 WARN]: [Slimefun] * the foreseeable future, so please update!
[16:25:43 WARN]: [Slimefun] ****************************************************
[16:25:43 INFO]: [Slimefun] Creating directories...
[16:25:43 INFO]: [Slimefun] Loading language files...
[16:25:43 ERROR]: Error occurred while enabling Slimefun vRC - 35 (git 5e901972) (Is it up to date?)
java.lang.NullPointerException: Profile name must not be null
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31) ~[authlib-5.0.47.jar:?

### 📑 Reproduction Steps

1. have java version 17-internal installed
2. have paper 1.20.2
3. add slimefun as plugin
4. run the server
5. server will load plugins
6. generating world
7. and some plugins will saying again include this slimefun has disabled

### 💡 Expected Behavior

can run in java 17-internal

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Slimefun4 - RC 35 (git 5e901)

### 🧭 Other plugins

via backwards multiverse

**Comment by J3fftw1** [comment]
Use the latest dev build. RC builds aren’t supported for issues and this issue is resolved in a dev build.
