### ISSUE TITLE
Explosive pickaxe duplicates elevator plate when breaking it (or in the explode range)

### ISSUE THREAD

**Issue by EienMiku** [Slimefun/Slimefun4#4037]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When I break a elevator plate or nearby block with an explosive pickaxe, the plate gets duplicated.

### 📑 Reproduction Steps

1. Break a elevator plate or nearby block with an explosive pickaxe.
2. The elevator plate got duplicated.

### 💡 Expected Behavior

The correct drops should be 1 of each, not 2.

### 📷 Screenshots / Videos

[21:52:55 ERROR]: [Slimefun] An Error occurred while copying a temporary File for Slimefun DEV - 1104 (git c977454e)
java.nio.file.AccessDeniedException: data-storage\Slimefun\stored-blocks\world\ELECTRIC_SMELTERY_2.sfb.tmp -> data-storage\Slimefun\stored-blocks\world\ELECTRIC_SMELTERY_2.sfb
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293) ~[?:?]
        at java.nio.file.Files.move(Files.java:1432) ~[?:?]
        at me.mrCookieSlime.Slimefun.api.BlockStorage.save(BlockStorage.java:336) ~[Slimefun4 - DEV 1104 (git c9774).jar:?]
        at io.github.thebusybiscuit.slimefun4.core.services.AutoSavingService.saveAllBlocks(AutoSavingService.java:95) ~[Slimefun4 - DEV 1104 (git c9774).jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-196]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Slimefun DEV - 1104 (git c977454e)

**Comment by Boomer-1** [comment]
please don't combine issues in one report. the error report has nothing to do with the explosive pickaxe. I can confirm the dupe.

the error appears to be related to windows locking the file preventing slimefun from getting access to it.

**Comment by EienMiku** [comment]
the bug mentioned elsewhere does exist,
sorry for my mistake about the wrong error report > <

**Comment by SrMonsterYT** [comment]
when will this be fixed, it's been around for 2 years now
