### ISSUE TITLE
Error on auto-saving data

### ISSUE THREAD

**Issue by masood151117** [Slimefun/Slimefun4#4164]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

```
`[10:35:47` INFO]: [Slimefun] Auto-saving block data... (Next auto-save: 10m)
[10:35:47 INFO]: [Slimefun] Saving block data for world "world" (20,401 change(s) queued)
[10:35:47 ERROR]: [Slimefun] An Error occurred while copying a temporary File for Slimefun Dev - 1143
java.nio.file.AccessDeniedException: data-storage\Slimefun\stored-blocks\world\DUST_EXTRACTOR.sfb.tmp -> data-storage\Slimefun\stored-blocks\world\DUST_EXTRACTOR.sfb
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293) ~[?:?]
        at java.nio.file.Files.move(Files.java:1432) ~[?:?]
        at me.mrCookieSlime.Slimefun.api.BlockStorage.save(BlockStorage.java:336) ~[Slimefun4-Dev.jar:?]
        at io.github.thebusybiscuit.slimefun4.core.services.AutoSavingService.saveAllBlocks(AutoSavingService.java:110) ~[Slimefun4-Dev.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2142]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2142]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:35:48 INFO]: [Slimefun] Auto-saved all player data for 4 player(s)!
`
```
In my server console, I s. Alopmeallowed RAMr flags startup 12G is the maximum allowed RAMr flags startup 12G is the maximum allowed RAMr flags startup 12G is the maximum allowed RAMr flags startup 12G is the maximum allowed RAMr flags startup 12G is the maximum allowed RAM

### 📑 Reproduction Steps

.

### 💡 Expected Behavior

.

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Dev 1143

**Comment by J3fftw1** [comment]
Go into the folder specified (in this case data-storage/Slimefun/world) and rename BLOCK.sfb.tmp to BLOCK.sfb. Override the existing file and boom. The updated file is there

If this doesnt work set the owner of the the folder data-storage to everyone and restart the server.
This is an windows issue we sadly can not resolve.
If this is your own server you should check if the file is locked.

Join the discord for more help if you need it

**Comment by masood151117** [comment]
ok tnx
