### ISSUE TITLE
Slimefun Build 1145 produces errors on Paper 1.20.6 (build #124)

### ISSUE THREAD

**Issue by CodingWithAnxiety** [Slimefun/Slimefun4#4199]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When starting a 1.20.6 server using paper, whilst having the latest Slimefun dev version installed, the following error occurs:

```java
[00:36:41 ERROR]: [dough: skins] Failed to detect skull nbt methods
java.lang.NoSuchMethodException: net.minecraft.world.level.block.entity.SkullBlockEntity.a(com.mojang.authlib.GameProfile)
	at java.base/java.lang.Class.getMethod(Class.java:2395) ~[?:?]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getMethod(AbstractDefaultRulesReflectionProxy.java:100) ~[reflection-rewriter-runtime-0.0.1.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getMethod(Unknown Source) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at Slimefun4-Dev(1).jar/io.github.thebusybiscuit.slimefun4.libraries.dough.skins.nms.PlayerHeadAdapter18.<init>(PlayerHeadAdapter18.java:23) ~[Slimefun4-Dev(1).jar:?]
	at Slimefun4-Dev(1).jar/io.github.thebusybiscuit.slimefun4.libraries.dough.skins.nms.PlayerHeadAdapter.get(PlayerHeadAdapter.java:31) ~[Slimefun4-Dev(1).jar:?]
	at Slimefun4-Dev(1).jar/io.github.thebusybiscuit.slimefun4.libraries.dough.skins.PlayerHead.<clinit>(PlayerHead.java:23) ~[Slimefun4-Dev(1).jar:?]
	at Slimefun4-Dev(1).jar/io.github.thebusybiscuit.slimefun4.utils.SlimefunUtils.getCustomHead(SlimefunUtils.java:246) ~[Slimefun4-Dev(1).jar:?]
	at Slimefun4-Dev(1).jar/io.github.thebusybiscuit.slimefun4.core.services.localization.Language.<init>(Language.java:52) ~[Slimefun4-Dev(1).jar:?]
	at Slimefun4-Dev(1).jar/io.github.thebusybiscuit.slimefun4.core.services.LocalizationService.<init>(LocalizationService.java:67) ~[Slimefun4-Dev(1).jar:?]
	at Slimefun4-Dev(1).jar/io.github.thebusybiscuit.slimefun4.implementation.Slimefun.onPluginStart(Slimefun.java:300) ~[Slimefun4-Dev(1).jar:?]
	at Slimefun4-Dev(1).jar/io.github.thebusybiscuit.slimefun4.implementation.Slimefun.onEnable(Slimefun.java:241) ~[Slimefun4-Dev(1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

In addition, having the Exotic Garden plugin installed furthers the issue. As exotic garden is a **community** plugin, I will not discuss it any further beyond the following pastebin link;
https://paste.ee/p/RiOjp

### 📑 Reproduction Steps

1. Prepare a base, 1.20.6, paper server. 
    - No configuration needs to be made to the server, minus eula=true
2. Launch the server. I am doing this using OpenJDK 21
3. Presented with error.

### 💡 Expected Behavior

No errors to occur during startup of the server.

### 📷 Screenshots / Videos

![image](https://github.com/Slimefun/Slimefun4/assets/78890450/227b0845-1595-43d7-9b57-1406e02a2d32)

https://github.com/Slimefun/Slimefun4/assets/78890450/47306bee-3dd8-42b5-832c-b3ee7ba6b793

I do not scroll within the video.

### 📜 Server Log

https://paste.ee/p/9RBoV

### 📂 `/error-reports/` folder

N/A

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

> slimefun versions
[00:52:07 INFO]: This Server uses the following setup of Slimefun:
Paper 1.20.6-124-0fcf3e3 (MC: 1.20.6)
Slimefun Dev - 1145
Java 21

Installed Addons: (1)
  ExoticGarden vDEV - 78 (git 7f9a5f63)

### 🧭 Other plugins

This error exists within both **ExoticGarden** alongside slimefun. I recall seeing outputted errors from **EcoPower**, however I did not have it installed in none of my logs which are linked here.

**Comment by CodingWithAnxiety** [comment]
Renamed. The server still works (assuming Exotic Garden isn't installed) however the errors still cocur.

**Comment by CodingWithAnxiety** [comment]
From the discord bugs channel:

Errors in the slimefun plugins folder are not documented as it does **not produce any errors within this folder.**

**Comment by JustAHuman-xD** [comment]
We don’t support 1.20.5+

**Comment by JustAHuman-xD** [comment]
Update is a WIP

**Comment by CodingWithAnxiety** [comment]
Got-cha. Well, I hope this report helps you trace down another bug.

**Comment by EpicPlayerA10** [comment]
The error lies in `dough` lib. Here is a PR that adds support for 1.20.6 https://github.com/Slimefun/dough/pull/271

**Comment by CodingWithAnxiety** [comment]
I thought it had something to do with dough considering the errors were being spat with dough's name in them. Good catch.

**Comment by Boomer-1** [comment]
since this was a dough issue, is there any reason to keep this open? additionally it's from an older version of slimefun

**Comment by WalshyDev** [comment]
We support 1.20.5/6 - closing
