### ISSUE TITLE
Slimefun generated an exception, flooding console with incomplete tasks.

### ISSUE THREAD

**Issue by anthonykour** [Slimefun/Slimefun4#4207]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Slimefun Build 1148, generated an exception while running a task.

`[21:46:39 WARN]: [Slimefun] Task #69905 for Slimefun vDev - 1148 generated an exception
java.lang.UnsupportedOperationException: Cannot update skin texture, no adapter found
        at Slimefun4-Dev.jar/io.github.thebusybiscuit.slimefun4.libraries.dough.skins.PlayerHead.setSkin(PlayerHead.java:72) ~[Slimefun4-Dev.jar:?]
        at Slimefun4-Dev.jar/io.github.thebusybiscuit.slimefun4.implementation.tasks.CapacitorTextureUpdateTask.setTexture(CapacitorTextureUpdateTask.java:79) ~[Slimefun4-Dev.jar:?]
        at Slimefun4-Dev.jar/io.github.thebusybiscuit.slimefun4.implementation.tasks.CapacitorTextureUpdateTask.run(CapacitorTextureUpdateTask.java:72) ~[Slimefun4-Dev.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1734) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:503) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

### 📑 Reproduction Steps

Run Slimefun 4 most recent build on version 1.20.6

### 💡 Expected Behavior

Render skin texture

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Slimefun Version: 1148

**Comment by ybw0014** [comment]
Slimefun doesnt support 1.20.6 yet.
