### ISSUE TITLE
Error with Block Ticker Task

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun/Slimefun4#4216]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

found an error in my console log

### 📑 Reproduction Steps

no idea what caused it

### 💡 Expected Behavior

 no error in logs

### 📜 Server Log

https://pastebin.com/UPY87LyM

### 📂 `/error-reports/` folder

none

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

dev 1148  
mc 1.20.4
java 22

**Comment by mcchampions** [comment]
the same issue:#3696 solve:#4173

**Comment by Boomer-1** [comment]
additional new data from 1.20.4 and dev 1157

11/30 9:18:15 PM [Error] : [Slimefun] An Exception was caught while ticking the Block Tickers Task for Slimefun vDev - 1157
11/30 9:18:15 PM [Error] java.util.ConcurrentModificationException: null
11/30 9:18:15 PM [Error] at java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
11/30 9:18:15 PM [Error] at java.util.HashMap$KeyIterator.next(HashMap.java:1628) ~[?:?]
11/30 9:18:15 PM [Error] at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:140) ~[Slimefun4-Dev (4).jar:?]
11/30 9:18:15 PM [Error] at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:110) ~[Slimefun4-Dev (4).jar:?]
11/30 9:18:15 PM [Error] at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-497]
11/30 9:18:15 PM [Error] at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-497]
11/30 9:18:15 PM [Error] at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
11/30 9:18:15 PM [Error] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
11/30 9:18:15 PM [Error] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
11/30 9:18:15 PM [Error] at java.lang.Thread.run(Thread.java:1583) ~[?:?]
