### ISSUE TITLE
1.21 not supported/不支持1.21

### ISSUE THREAD

**Issue by XZH2024** [Slimefun/Slimefun4#4219]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

服务端类型是Leaf

The server software is Leaf

[11:08:36 ERROR]: [Slimefun] ****************************************************
[11:08:36 ERROR]: [Slimefun] * Slimefun was not installed correctly!
[11:08:36 ERROR]: [Slimefun] * You are using the wrong version of Minecraft!
[11:08:36 ERROR]: [Slimefun] *
[11:08:36 ERROR]: [Slimefun] * You are using Minecraft 1.21.x
[11:08:36 ERROR]: [Slimefun] * but Slimefun Dev - 1148 requires you to be using
[11:08:36 ERROR]: [Slimefun] * Minecraft 1.16.x / 1.17.x / 1.18.x / 1.19.x / 1.20.x
[11:08:36 ERROR]: [Slimefun] ****************************************************
[11:08:36 INFO]: [Slimefun] Disabling Slimefun vDev - 1148
[11:08:36 ERROR]: Error occurred while disabling Slimefun vDev - 1148
java.lang.NullPointerException: Cannot read the array length because "<local2>" is null
        at Slimefun4-Dev.jar/io.github.thebusybiscuit.slimefun4.core.services.BackupService.createBackup(BackupService.java:84) ~[Slimefun4-Dev.jar:?]
        at Slimefun4-Dev.jar/io.github.thebusybiscuit.slimefun4.core.services.BackupService.run(BackupService.java:67) ~[Slimefun4-Dev.jar:?]
        at Slimefun4-Dev.jar/io.github.thebusybiscuit.slimefun4.implementation.Slimefun.onDisable(Slimefun.java:453) ~[Slimefun4-Dev.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[leaf-1.21.jar:1.21-DEV-d17d9c1]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[leaf-1.21.jar:1.21-DEV-d17d9c1]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at Slimefun4-Dev.jar/io.github.thebusybiscuit.slimefun4.implementation.Slimefun.onEnable(Slimefun.java:238) ~[Slimefun4-Dev.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[leaf-1.21.jar:1.21-DEV-d17d9c1]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaf-1.21.jar:1.21-DEV-d17d9c1]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:658) ~[leaf-1.21.jar:1.21-DEV-d17d9c1]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:607) ~[leaf-1.21.jar:1.21-DEV-d17d9c1]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:742) ~[leaf-1.21.jar:1.21-DEV-d17d9c1]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:504) ~[leaf-1.21.jar:1.21-DEV-d17d9c1]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:378) ~[leaf-1.21.jar:1.21-DEV-d17d9c1]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[leaf-1.21.jar:1.21-DEV-d17d9c1]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.jar:1.21-DEV-d17d9c1]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

### 📑 Reproduction Steps

将slimefun丢进plugins文件夹内
启动服务器
报错

Drop slimefun into the plugins folder
Start the server
Error

### 💡 Expected Behavior

应该被正确加载

Should be loaded correctly

### 📷 Screenshots / Videos

![image](https://github.com/user-attachments/assets/115a1a35-ec36-4798-ae1c-5195e1043649)

### 📜 Server Log

https://pastebin.com/ViSLbzTD

### 📂 `/error-reports/` folder

none

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Bulid 1148
![image](https://github.com/user-attachments/assets/37a8daaa-ed05-431a-a274-c4af39851834)

**Comment by Boomer-1** [comment]
leaf is not supported, and slimefun is being updated to support 1.21.

**Comment by Outfit8TSB** [comment]
@XZH2024 if i were you, i would just used [PlazmaMC](https://github.com/PlazmaMC/PlazmaBukkit) or [LeavesMC](https://github.com/LeavesMC/Leaves).
