### ISSUE TITLE
bug sf head

### ISSUE THREAD

**Issue by aliakbartnt** [Slimefun/Slimefun4#4224]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I downloaded the official version from the new build site [Blob Builds](https://blob.build/).
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

! [Tue 17:15:16 WARN  Slimefun] Task #217122083 for Slimefun vDEV - 1104 (git c977454e) generated an exception
java.lang.UnsupportedOperationException: Cannot update skin texture, no adapter found
    at Slimefun4 - DEV 1104 (git c9774).jar//io.github.thebusybiscuit.slimefun4.libraries.dough.skins.PlayerHead.setSkin(PlayerHead.java:72)
    at Slimefun4 - DEV 1104 (git c9774).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.CapacitorTextureUpdateTask.setTexture(CapacitorTextureUpdateTask.java:79)
    at Slimefun4 - DEV 1104 (git c9774).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.CapacitorTextureUpdateTask.run(CapacitorTextureUpdateTask.java:69)
    at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1734)
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:503)
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260)
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
    at java.base/java.lang.Thread.run(Thread.java:1583)

### 📑 Reproduction Steps

my server ver 1.20.6 purpur

### 💡 Expected Behavior

hi i fix dis pls help me . some head slimefun not load and steve head

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Slimefun4 - DEV 1104

**Comment by Boomer-1** [comment]
also update slimefun to the latest version. then please confirm whether you are still having the same issue or not
if we don't hear back we'll assume it's working as intended.

**Comment by WalshyDev** [comment]
It does support 1.20.6 - https://blob.build/project/Slimefun4

Please update, you're on an old version.
