### ISSUE TITLE
block tickers task error

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun/Slimefun4#4276]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I downloaded the official version from the new build site [Blob Builds](https://blob.build/).
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

found this error in my console quite frequently, but not sure what's triggering it. it may also be tied to #4216

12/22 3:14:56 PM [Error] : [Slimefun] An Exception was caught while ticking the Block Tickers Task for Slimefun vDev - 1157
12/22 3:14:56 PM [Error] java.util.ConcurrentModificationException: null
12/22 3:14:56 PM [Error] at java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
12/22 3:14:56 PM [Error] at java.util.HashMap$KeyIterator.next(HashMap.java:1628) ~[?:?]
12/22 3:14:56 PM [Error] at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:140) ~[Slimefun4-Dev (4).jar:?]
12/22 3:14:56 PM [Error] at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:110) ~[Slimefun4-Dev (4).jar:?]
12/22 3:14:56 PM [Error] at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-497]
12/22 3:14:56 PM [Error] at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-497]
12/22 3:14:56 PM [Error] at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
12/22 3:14:56 PM [Error] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
12/22 3:14:56 PM [Error] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
12/22 3:14:56 PM [Error] at java.lang.Thread.run(Thread.java:1583) ~[?:?]
12/22 3:16:29 PM [Info] : [Netheopoiesis] Netheopoiesis saving data.
12/22 3:16:29 PM [Info] : [DankTech2] DankTech2 saving data.
12/22 3:16:29 PM [Info] : [CrystamaeHistoria] Crystamae saving data.
12/22 3:16:29 PM [Info] : [EMCTech] EMCTech saving data.
12/22 3:16:52 PM [Error] : [Slimefun] An Exception was caught while ticking the Block Tickers Task for Slimefun vDev - 1157
12/22 3:16:52 PM [Error] java.util.ConcurrentModificationException: null
12/22 3:16:52 PM [Error] at java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
12/22 3:16:52 PM [Error] at java.util.HashMap$KeyIterator.next(HashMap.java:1628) ~[?:?]
12/22 3:16:52 PM [Error] at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:140) ~[Slimefun4-Dev (4).jar:?]
12/22 3:16:52 PM [Error] at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:110) ~[Slimefun4-Dev (4).jar:?]
12/22 3:16:52 PM [Error] at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-497]
12/22 3:16:52 PM [Error] at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-497]
12/22 3:16:52 PM [Error] at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
12/22 3:16:52 PM [Error] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
12/22 3:16:52 PM [Error] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
12/22 3:16:52 PM [Error] at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### 📑 Reproduction Steps

no clue what's causing it

### 💡 Expected Behavior

no error

### 📷 Screenshots / Videos

none

### 📜 Server Log

no other errors

### 📂 `/error-reports/` folder

nothing in error reports

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

dev 1157

### 🧭 Other plugins

none that i can tell.

**Comment by DereC4** [comment]
Created a PR for it
